# Generated by Django 5.1.7 on 2025-03-15 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ghlauthcredentials',
            name='token_timestamp',
        ),
        migrations.RemoveField(
            model_name='ghlauthcredentials',
            name='token_type',
        ),
        migrations.AlterField(
            model_name='ghlauthcredentials',
            name='access_token',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='ghlauthcredentials',
            name='company_id',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='ghlauthcredentials',
            name='expires_in',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='ghlauthcredentials',
            name='location_id',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='ghlauthcredentials',
            name='refresh_token',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='ghlauthcredentials',
            name='scope',
            field=models.CharField(blank=True, default='', max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='ghlauthcredentials',
            name='user_id',
            field=models.CharField(default='', max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='ghlauthcredentials',
            name='user_type',
            field=models.CharField(blank=True, default='', max_length=50, null=True),
        ),
    ]
