# Generated by Django 5.1.7 on 2025-03-18 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('serviceM8', '0005_alter_client_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='mobile',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
    ]
