# Generated by Django 5.1.7 on 2025-03-19 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('serviceM8', '0006_client_mobile'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceM8Log',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('event_type', models.CharField(max_length=100)),
                ('status', models.CharField(max_length=50)),
                ('job_uuid', models.CharField(blank=True, max_length=100, null=True)),
                ('client_uuid', models.CharField(blank=True, max_length=100, null=True)),
                ('servicem8_data', models.TextField(blank=True, null=True)),
                ('job_link_successful', models.BooleanField(default=False)),
                ('client_link_successful', models.BooleanField(default=False)),
                ('ghl_job_id', models.CharField(blank=True, max_length=100, null=True)),
                ('ghl_client_id', models.CharField(blank=True, max_length=100, null=True)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('stack_trace', models.TextField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['timestamp'], name='serviceM8_s_timesta_2b4f26_idx'), models.Index(fields=['event_type'], name='serviceM8_s_event_t_d5dd6e_idx'), models.Index(fields=['job_uuid'], name='serviceM8_s_job_uui_567c1e_idx'), models.Index(fields=['client_uuid'], name='serviceM8_s_client__abf8a8_idx'), models.Index(fields=['status'], name='serviceM8_s_status_4fec1e_idx')],
            },
        ),
    ]
